version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    expose:
      - "80"
    depends_on:
      - snapintel-api-1
      - snapintel-api-2
      - snapintel-api-3
    restart: unless-stopped

  snapintel-api-1:
    build: .
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - INSTANCE_ID=1
    restart: unless-stopped

  snapintel-api-2:
    build: .
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - INSTANCE_ID=2
    restart: unless-stopped

  snapintel-api-3:
    build: .
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - INSTANCE_ID=3
    restart: unless-stopped
